---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Dev
  region: us-west-2
  version: "1.21"

iam:
  withOIDC: true

addons:
- name: vpc-cni # no version is specified so it deploys the default version
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest

managedNodeGroups:
- name: mng1
  desiredCapacity: 2
  instanceType: t3.small
  privateNetworking: true

# To enable all of the control plane logs, uncomment below:
cloudWatch:
 clusterLogging:
   enableTypes: ["*"]
